<!--
Copyright 2016 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID: jqueryform-7be94b
Date: 2016-10-06 10:33:58
Generated by http://www.jqueryform.com
-->
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="generator" content="jqueryform.com">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="ROBOTS" content="NOINDEX, NOFOLLOW">
  <meta name="description" content="landing page for setting up a meeting to engage with The Allan Wade Company">
  <link rel="canonical" href="http://www.allan-wade.com/landing-pages/engage/engage.php">

  <title>Weekly Marketing Scorecard | The Allan Wade Company</title>
  

  <!-- Bootstrap -->
  <!-- Bootstrap -->
<link href="http://www.allan-wade.com/css/awstyle.css" rel="stylesheet"> 
<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha384-+ENW/yibaokMnme+vBLnHMphUYxHs34h9lpdbSLuAwGkOKFRl4C34WkjazBtb7eT" crossorigin="anonymous"></head>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.0/css/bootstrap-datepicker3.min.css" rel="stylesheet">
  

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <link href="vendor.css" rel="stylesheet">

</head>

<body> 
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-62132429-1', 'auto');
  ga('send', 'pageview');

</script>

<!-- ----------------------------------------------- -->
<div class="container jf-form">
  <h1>The Weekly Marketing Scorecard</h1>
  <p class="lead">A scorecard is one step to transforming your thoughts and plans into action and dones!</p>
</div>
<div class="container jf-form">
<form data-licenseKey="" name="jqueryform-7be94b" id="jqueryform-7be94b" action='admin.php' method='post' enctype='multipart/form-data' novalidate autocomplete="on">
<input type="hidden" name="method" value="validateForm">
<input type="hidden" id="serverValidationFields" name="serverValidationFields" value="">



<div class="form-group c1 required" data-cid="c1">
  <label class="control-label" for="c1">Your Name</label>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-user"></i> </span>
<input type="text" class="form-control" id="c1" name="c1" value=""    
    data-rule-required="true"  />
</div>
</div>

<div class="form-group c2 required" data-cid="c2">
  <label class="control-label" for="c2">Email</label>

<div class="input-group"><span class="input-group-addon left"><i class="glyphicon glyphicon-envelope"></i> </span>
<input type="email" class="form-control" id="c2" name="c2" value=""   
    data-rule-email="true" 
    data-rule-required="true"  />
</div>
  
</div>

<div class="form-group submit c100 " data-cid="c100" style="position: relative;">
  <label class="control-label sr-only" for="c100" style="display: block;">Submit Button</label>

  <div class="progress" style="display: none; z-index: -1; position: absolute;">
    <div class="progress-bar progress-bar-striped active" role="progressbar" style="width:100%">
    </div>
  </div>

  <button type="submit" class="btn btn-primary btn-lg" style="z-index: 1;">
  		Download!
  </button>

  <p class="error bg-warning" style="display:none;">
    Please check the required fields.  </p>
  
</div>

</form>

<a href="http://www.jqueryform.com" target="_blank" class="jf-copyright">Powered by jqueryform.com</a>
</div>

<div class="container jf-thankyou" style="display:none;" data-redirect="http%3A%2F%2Fwww.allan-wade.com%2Fengage-thank-you.php" data-seconds="10">
  <h3>Your form has been submitted. Thank You!</h3>
  <p>Here is your file: <a href="http://www.allan-wade.com/landing-pages/weekly-marketing-scorecard/weekly-marketing-scorecard.pdf">Weekly Marketing Scorecard</a></p>
</div>
<!-- ----------------------------------------------- -->
    <div class="container jf-form" style="padding: 15px 0px 45px 0px;">
        <footer style="border-top: 1px solid silver; padding-top: 15px;">
            <p>Copyright &copy; 2016 The Allan Wade Company, all rights reserved | Contact information: <a href="mailto:info@allan-wade.com">info@allan-wade.com</a></p>
        </footer>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.0/js/bootstrap-datepicker.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.min.js"></script>
<script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/additional-methods.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-scrollTo/2.1.0/jquery.scrollTo.min.js"></script>
<script src="vendor.js" ></script>

<script src="jqueryform.com.min.js?ver=v1.0-rc24&id=jqueryform-7be94b" ></script>


<script type="text/javascript">

	// start jqueryform initialization
	// --------------------------------
	JF.init('#jqueryform-7be94b');

	// watch form element change event to run jqueryform's formlogic
	// ---------------------------------------------------------------
	var logics = [
    {
        "disabled": false,
        "action": "",
        "selector": "",
        "match": "",
        "rules": [

        ]
    }
];
	$('input,input:radio,select').change(function(){
		$.formlogic( {logics: logics} );
	});
</script>

  </body>
</html>